CREATE DATABASE TESTE

USE TESTE

CREATE TABLE DEPARTAMENTO (
CODDEPARTAMENTO INT PRIMARY KEY,
NOMEDEPTO VARCHAR(50)
)
CREATE table FUNCIONARIO(
CODFUNCIONARIO int PRIMARY KEY,
NOME VARCHAR(50),
SALARIO DECIMAL(10,2),
CODDEPARTAMENTO INT,
FOREIGN KEY (coddepartamento) references departamento (coddepartamento)
)
INSERT INTO DEPARTAMENTO VALUES (1,'VENDAS')
INSERT INTO DEPARTAMENTO VALUES (2,'RECURSOS HUMANOS')
INSERT INTO FUNCIONARIO VALUES (1,'FUNCIONARIO 1',2500,2)
INSERT INTO FUNCIONARIO VALUES (2,'FUNCIONARIO 2',4850,1)
INSERT INTO FUNCIONARIO VALUES (3,'FUNCIONARIO 3',5400,2)
INSERT INTO FUNCIONARIO VALUES (4,'FUNCIONARIO 4',3950,2)

INSERT INTO FUNCIONARIO VALUES (1,'FUNCIONARIO 1',2500,2)
INSERT INTO FUNCIONARIO VALUES (2,'FUNCIONARIO 2',4850,1)
INSERT INTO FUNCIONARIO VALUES (3,'FUNCIONARIO 3',5400,2)
INSERT INTO FUNCIONARIO VALUES (4,'FUNCIONARIO 4',3950,2)
INSERT INTO FUNCIONARIO VALUES (5,'FUNCIONARIO 5',4860,1)
INSERT INTO FUNCIONARIO VALUES (6,'FUNCIONARIO 6',6400,2)
INSERT INTO FUNCIONARIO VALUES (7,'FUNCIONARIO 7',7950,2)


-- SUM, AVG e COUNT(expr) permitem especificar também o operador DISTINCT
select count(distinct coddepartamento)
from funcionario

select count(*) 'Quantidade Funcionário', CodDepartamento
from funcionario
GROUP BY CodDepartamento

SELECT * FROM DEPARTAMENTO 